version: '3'
services:
    web:
        image: nginx:alpine
        container_name: tnr-web
        volumes:
            - "./web:/var/www/html:ro"
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
        labels:
            - "traefik.docker.network=traefik"
            - "traefik.frontend.rule=Host:demo.netwerkdigitaalerfgoed.nl;PathPrefix:/termennetwerk/reconciliation;PathPrefixStrip:/termennetwerk/reconciliation"
            - "traefik.port=80"
        networks:
            - traefik
        depends_on:
            - php

    php:
        build: php-fpm
        container_name: tnr-php-fpm
        volumes:
            - "./web:/var/www/html:ro"
        networks:
            - traefik

networks:
  traefik:
    external: true
